### ISSUE TITLE
Documentation error (publish tileset)

### ISSUE THREAD

**Issue by mapoulos** [mapbox/tilesets-cli#106]
I'm not sure where else to report this. The docs for the [MTS publish endpoint](https://docs.mapbox.com/api/maps/#response-publish-a-tileset) mistakenly identify the `jobId` parameter as `job_id`. It should be `jobId`.

I realize this is in beta and things are subject to change: but I thought I'd flag this since I noticed it this morning.

**Comment by Gerdie** [comment]
Thanks for reporting this @mapoulos -- it has been fixed.
