### ISSUE TITLE
Question: should the README be reordered to match the flow in our documentation?

### ISSUE THREAD

**Issue by samfader** [mapbox/tilesets-cli#12]
Our docs outline a flow for using the Tilesets API: https://docs.mapbox.com/api/maps/#tilesets

1. Create a tileset source
2. Write a recipe
3. Create a new tileset
4. Publish the tileset

The README in this repo goes like this:

1. Create a tileset
2. Create a tileset source
3. Write a recipe

Does it make sense to re-order the README to more closely match our mapbox.com docs?

**Comment by mapsam** [comment]
@samfader 👍 on reordering
