### ISSUE TITLE
Returned message when creating/publishing tilesets includes a period

### ISSUE THREAD

**Issue by samfader** [mapbox/tilesets-cli#13]
I'm working on creating and publishing my tileset and noticed that the response object contains a `.` that might be slightly confusing. For example, when creating:

```
{
  "message": "Successfully created samf.rivers_and_lakes_centerlines_mts."
}
```

And when publishing:

```
{
  "jobId": "cjz34qt4o000301qreu6z9h3t",
  "message": "Processing samf.rivers_and_lakes_centerlines_mts."
}
```

My tileset ID is `samf.rivers_and_lakes_centerlines_mts`, not `samf.rivers_and_lakes_centerlines_mts.`. Not a huge thing, but could see it being a bit confusing.

This doesn't happen when using `tilesets status`:

```
{
  "failed": 0,
  "id": "samf.rivers_and_lakes_centerlines_mts",
  "last_completed_job": null,
  "processing": 1,
  "queued": 0,
  "success": 0
}
```

**Comment by mapsam** [comment]
This is a response from the Tilesets API, we can remove the period there!

**Comment by suhasdeshpande** [comment]
@samfader please let us know if you still see period. We have fixed this issue.

**Comment by samfader** [comment]
Thanks @suhasdeshpande @mapsam!
