### ISSUE TITLE
Erorr message if access tokens does not have permissions

### ISSUE THREAD

**Issue by lukasmartinelli** [mapbox/tilesets-cli#15]
Right now you simply get a "Not found" error instead of "Permission denied" for any command that could inform you that your  access token does not have sufficient permissions.

**Comment by mapsam** [comment]
@lukasmartinelli are you certain this is a bug? If you are using an access token from one account, and attempt to interact with a tileset/tileset-source from another account, the Mapbox APIs will return a 404 Not Found as to not reveal if a private resource exists or not.

**Comment by lukasmartinelli** [comment]
> @lukasmartinelli are you certain this is a bug? If you are using an access token from one account, and attempt to interact with a tileset/tileset-source from another account, the Mapbox APIs will return a 404 Not Found as to not reveal if a private resource exists or not.

Fair. Down to close.
