### ISSUE TITLE
Invalid Syntax After Following Installation Steps

### ISSUE THREAD

**Issue by chrwebb** [mapbox/tilesets-cli#17]
I've followed the installation instructions for tilesets-cli both inside and outside of a virtual environment but have had syntax errors when trying to use the tool in any capacity.

These are the instructions I have followed.
`git clone git@github.com:mapbox/tilesets-cli.git`
`cd tilesets-cli`
`pip install .`
`tilesets --help`

But after running `tilesets --help` I get this.
``$ tilesets --help
Traceback (most recent call last):
  File "/usr/local/bin/tilesets", line 6, in <module>
    from tilesets.cli import cli
  File "/usr/local/lib/python2.7/dist-packages/tilesets/cli.py", line 89
    click.echo(f'You can view the status of your tileset with the `tilesets status {tileset}` command.')
                                                                                                      ^
SyntaxError: invalid syntax
``

I am running Python 3.6.7. There were no errors or warnings when installing dependencies with pip. I've tried commenting out the initial problem line, as it appears to just be a piece of inconsequential output, but that just leads to a different syntax error when running any `tilesets` functions.

**Comment by springmeyer** [comment]
Hi @chrwebb - as you likely noticed the `tilesets-cli` requires Python >= 3.6 (https://github.com/mapbox/tilesets-cli#requirements).

Thanks for sharing your error message. I notice:

> from tilesets.cli import cli File "/usr/local/lib/python2.7/dist-packages/tilesets/cli.py"

Which has `python2.7` in the path. So, I think what is happening is that you installed for python2 instead. You may need to run `python3 -m pip install .` or `pip3 install .` to actually install for python3.

**Comment by chrwebb** [comment]
Oh, of course! I should have been able to spot that problem myself. Reinstalling tilesets-cli dependencies by using `python3 -m pip install .` solved my issue.

Thanks for the quick and straightforward response!
