### ISSUE TITLE
SSL SSLEOFE Error When uploading data

### ISSUE THREAD

**Issue by bharkema** [mapbox/tilesets-cli#182]
Hi I am trying to upload my tileset data which is quite large 3GB in total and have split it into smaller chunks. of 600 to 800MB I have installed the Mapbox Tilesets CLI tool and it is running well but when it starts uploading the file I receive the following error:

`requests.exceptions.SSLError: HTTPSConnectionPool(host='api.mapbox.com', port=443): Max retries exceeded with URL: /tilesets/v1/sources/XXXXX/100x100_grid?access_token=XXXXXXXXXXXXX. XXXXXXXXXX (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2423)'))))`

Steps taken to try and fix:
- Update requests (2.32.2)
- Update certifi (2024.6.2)
- Reinstall

None of the above helped me fix the issue, des anyone have the same experience?

**Comment by bharkema** [comment]
I was able to fix the problem, but it seems there is still room for improvement.

It came down to the fact that the token i was using did not have the correct write permissions. i found this out after using a much smaller set then the 800MB file that i was originally using. where i received a normal error stating my token did not have the correct permissions. it seems that after a certain size the API from mapbox does not respond correctly.

**Comment by rhwang201** [comment]
This issue still exists and happened for my 90M file. Would much prefer a more informative error message
