### ISSUE TITLE
tilesets cli aborts connection with api on large source data uploads

### ISSUE THREAD

**Issue by dnomadb** [mapbox/tilesets-cli#31]
```
requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
```

**Comment by JamesChevalier** [comment]
I'm seeing a fair amount of these, as well as `Connection reset by peer` errors.

My workflow is iterating over 357 users and generating two tilesets for each user (public vs private data). I'm only _about_ a third of the way through, and I've seen it fail for about 20 users.

I'd be happy to provide more info if you need it.

**Comment by Gerdie** [comment]
possibly related:
- https://github.com/psf/requests/issues/2422 [unresolved]
- https://github.com/urllib3/urllib3/pull/1524 [PR open]

**Comment by cmtoomey** [comment]
I observed a similar error

`string longer than N bytes`

![image](https://user-images.githubusercontent.com/12201602/72828509-a656ec80-3c31-11ea-8442-c1ee0ae01a74.png)

**Comment by dnomadb** [comment]
> string longer than N bytes

This is likely due to the way we are reading input into a memory file for upload.

**Comment by Gerdie** [comment]
This has been improved in `0.3.4` -- if you are still seeing errors here, please open a new issue and note the size of the file you're uploading.
