### ISSUE TITLE
Add Recipe to existing Tileset

### ISSUE THREAD

**Issue by luciofncnd** [mapbox/tilesets-cli#33]
Hi, I'm using the Tileset CLI and would like to know if there is a way to add a Recipe to an existing Tileset.
Already have assigned the Tileset to a big number of Layers on different Styles and don't want to recreate the maps.

We have a dataset with 70k plus points and the Tileset automatically sets the zoom extent to z10 ~ z15 and it is not enough for us. We need more detail.

Also would like to suggest an UI function to adjust Zoom leves of the Tileset directly on the Tileset section of the Studio Web app.

Thanks in advance

**Comment by nuistzhou** [comment]
Yes, you could use Tileset CLI to update the recipe by calling `update-recipe` command together with a json file which describes the `minzoom` and `maxzoom` attributes. See more detailed doc here: https://docs.mapbox.com/help/troubleshooting/adjust-tileset-zoom-extent/

**Comment by dianeschulze** [comment]
Thanks for this ticket @luciofncnd . #71 added a link to the main [Mapbox Tiling Service docs](https://docs.mapbox.com/mapbox-tiling-service/overview/), which cover workflows in more detail.

Please note that you can only update the recipe of a tileset that was created with the Mapbox Tiling Service, either via the mapbox-tilesets CLI or the Tilesets API. You cannot add a recipe to a tileset that was created another way, e.g. in the Mapbox Studio UI. #71 also identified the commands that only support tilesets created with the Mapbox Tiling Service.

I've noted your request for a UI to help with recipe editing as well.

I hope this helps. Please re-open this if you have any remaining questions or requests.
