### ISSUE TITLE
Error information when use `tileset update-recipe` command for existing tileset

### ISSUE THREAD

**Issue by nuistzhou** [mapbox/tilesets-cli#35]
See error msg followed:

```python
  File "/Users/username/anaconda3/lib/python3.7/site-packages/tilesets/scripts/cli.py", line 286, in update_recipe
    raise errors.TilesetsError(r.text)
tilesets.errors.TilesetsError: {"message":"Unable to perform action. {tileset_id} was not created with the /tilesets/v1 endpoint."}
```

**Comment by dianeschulze** [comment]
Thanks for this ticket @nuistzhou. Certain commands (`update-recipe`, `publish`, `job`, and `jobs`) only support tilesets that were created with the [Mapbox Tiling Service](https://docs.mapbox.com/mapbox-tiling-service/), either via the Tilesets API or the mapbox-tilesets CLI. You will see an error message if you use these commands with a tileset that was created another way, e.g. in Mapbox Studio.
 
#71 updated the README and command helptext to identify the commands that only support tilesets created with MTS.

I hope this helps. Please re-open this if you have any more questions or requests.

**Comment by elgabato** [comment]
why I'm getting invalid recipe? 
{
  "version": 1,
  "layers": {
    "hello-tile": {
      "source": "mapbox://tileset-source/{username}/hello-tile",
      "minzoom": 4,
      "maxzoom": 8
    }
  }
}
the problem was with "hello-tile"

 "errors": ["layers.hello-tile.source does not belong to account 'myaccount'."]

hoping to get some answers.
