### ISSUE TITLE
documentation unclear on how to update a source

### ISSUE THREAD

**Issue by gasagna** [mapbox/tilesets-cli#37]
Hi, 

it is not clear to me from the README how I should update a source. What I do currently is `delete-source` followed by `add-source`, but it is unclear if there is a better way and if the recipes using the source in question have to be updated too.

Thanks.

**Comment by dianeschulze** [comment]
Thanks for this ticket @gasagna . #71 added a link to the main [Mapbox Tiling Service docs](https://docs.mapbox.com/mapbox-tiling-service/), which cover workflows in more depth.

Your workflow of `delete-source` followed by `add-source` work great. Just make sure the source is not used in any running jobs when you delete it. You only need to update the recipe if the name of the source changes.

Hope this helps. Please re-open this if you have any remaining questions or requests.
