### ISSUE TITLE
The example "High density points for data visualization (data reduction)" seems to be invalid

### ISSUE THREAD

**Issue by another-dave** [mapbox/tilesets-cli#38]
I've just installed the Tilesets CLI and trying to add a recipe to an existing tileset.
If I copy the example recipe from the docs for [High density points for data visualization (data reduction)](https://docs.mapbox.com/help/troubleshooting/tileset-recipe-examples/#high-density-points-for-data-visualization-data-reduction), I get an error on validation

## Steps to reproduce

* Create example recipe file as per docs:

```json
{
  "version": 1,
  "layers": {
    "dots": {
      "source": "mapbox://tileset-source/{username}/high-density-points-data",
      "minzoom": 0,
      "maxzoom": 15,
      "tiles": {
        "limit": [
          [ "lowest_where_in_distance", true, 50000, null ]
        ]
      }
    }
  }
}
```

* Swap in my username and tileset name and save
* Run `tilesets validate-recipe example.json` 

### Expected outcome

* Tileset recipe validates correctly

### Current outcome

* Validation fails with an error:

```json
{"valid": false, "errors": ["recipe.tiles.limit attribute value \"null\" is not a string."]}
```

### Version info 
This is usign tilesets v0.3.3 (cloned from master)

**Comment by brsbl** [comment]
Thanks for opening this ticket @another-dave ! We're currently working on a large revamp of all of our recipe examples and will include updating this recipe as part of that work.

**Comment by brsbl** [comment]
We recently released a big revamp of our recipe examples: https://docs.mapbox.com/help/troubleshooting/tileset-recipe-examples/, so I'm closing this ticket.

**Comment by another-dave** [comment]
> We recently released a big revamp of our recipe examples: https://docs.mapbox.com/help/troubleshooting/tileset-recipe-examples/, so I'm closing this ticket.

Hi @brsbl, thanks for following up & will dig into the new examples when I get a chance.

Just an FYI that you've a broken link for sample data download under (_[NYC points of interest — reducing feature density](https://docs.mapbox.com/mapbox-tiling-service/examples/points-of-interest/)_) 

-  Under "Download the data you'll use to create the tileset", the **Download data** button links through to https://mts-recipe-examples.s3.amazonaws.com/nyc_pois.ldgeojson and gives an AWS S3 error:

```xml
<Error>
    <Code>NoSuchBucket</Code>
    <Message>The specified bucket does not exist</Message>
    <BucketName>mts-recipe-examples</BucketName>
    <RequestId>E4F85C6603569577</RequestId>
    <HostId>
        bl7+iGoid6INZwb7BeZbxEOgNKqNNsGK0sK3s4/3Brmjzc48U7fVb6X3aEN9hyRMoXbOCf9kyrM=
    </HostId>
</Error>
```

**Comment by millzpaugh** [comment]
@another-dave - fixing this link now! will let you know when it's updated on the site.

**Comment by millzpaugh** [comment]
confirmed this download link works now! https://docs.mapbox.com/mapbox-tiling-service/examples/points-of-interest/
