### ISSUE TITLE
add `--force` to `delete-source` to avoid asking confirmation to user 

### ISSUE THREAD

**Issue by gasagna** [mapbox/tilesets-cli#40]
Hi, 

Thanks for these tools, very useful.

Now that #26 has been merged, it is not possible to execute a `tilesets delete-source` command in a background script. Adding a `--force` or `--no-confirm` command line option to bypass the user confirmation would probably help.

Thanks!

**Comment by Gerdie** [comment]
this has been added in `0.3.5`
