### ISSUE TITLE
Error: no such option: --no-validation

### ISSUE THREAD

**Issue by tb4764** [mapbox/tilesets-cli#46]
Hi;

I'm trying to create a tileset from a shape file (.zip), so I'm using the --no-validation flag (v 0.3.5), but I get the error:

Usage: tilesets [OPTIONS] COMMAND [ARGS]...
Try 'tilesets --help' for help.

Error: no such option: --no-validation

Any fix to this?

**Comment by dianeschulze** [comment]
👋 Hi @tb4764 , per the [readme](https://github.com/mapbox/tilesets-cli#add-source
), source files must be geojson or line-delimited geojson:
> Adds GeoJSON files to a source for tiling. Accepts line-delimited GeoJSON or GeoJSON feature collections as files or via stdin. The CLI automatically converts data to line-delimited GeoJSON prior to uploading.

If you're still having trouble creating a tileset source from a geojson or line-delimited geojson files, please post the full command and output so we can better understand.
