### ISSUE TITLE
Incorrect information about pricing?

### ISSUE THREAD

**Issue by stevage** [mapbox/tilesets-cli#48]
> Set the privacy of the tileset. Allowed values are private and public. If not provided, will default to your plan level on Mapbox.com. Pay-As-You-Go plans only support public maps.

My understanding is "pay-as-you-go" plans don't really exist anymore, and anyone can make private tilesets?

**Comment by dianeschulze** [comment]
Thanks for pointing this out @stevage! These docs were updated in #71
