### ISSUE TITLE
Display progress when uploading a source

### ISSUE THREAD

**Issue by tristen** [mapbox/tilesets-cli#80]
For larger files, some status of progress would be helpful. In some cases, this can hang for a while:

<img width="697" alt="Screen Shot 2020-07-08 at 5 10 52 PM" src="https://user-images.githubusercontent.com/61150/86970793-fbce7980-c13d-11ea-894d-b3b1b0425581.png">

**Comment by mapsam** [comment]
Heya @tristen https://github.com/mapbox/tilesets-cli/pull/64 is a first pass at this! I'd be happy to merge and release, if you think it looks helpful.

**Comment by tristen** [comment]
@mapsam oh heck yes!!

**Comment by tristen** [comment]
Closing as https://github.com/mapbox/tilesets-cli/pull/64 is in
