### ISSUE TITLE
Display last modified date when running status

### ISSUE THREAD

**Issue by tristen** [mapbox/tilesets-cli#81]
If I run `tileset status` it would be nice to see the last modified date/time. The latest job id doesn’t mean anything to me if I hadn’t previously kept a record of it.

<img width="707" alt="Screen Shot 2020-07-08 at 5 15 58 PM" src="https://user-images.githubusercontent.com/61150/86971172-b2caf500-c13e-11ea-8277-833ca9604e90.png">

**Comment by jakepruitt** [comment]
We've removed the status endpoint and modified the status command to internally call the jobs endpoint. For anyone that wants `last modified` information, they can use the `tilesets jobs` command to get more detail.
